### ISSUE TITLE
Rename CubeServer to PyriteServer

### ISSUE THREAD

**Issue by obsoleted** [PyriteServer/PyriteServer#12]

**Comment by stefangordon** [comment]
Make sure to do a git-mv on any new folder or file renames to keep history.

**Comment by stefangordon** [comment]
Moving to m2, because, this is clearly not important :)

**Comment by obsoleted** [comment]
Resolved with:
c591a5b: Rename project, solution and namespace (CubeServer -> PyriteServer)
685086a: Rename directories, assemblies (CubeServer -> PyriteServer)
